version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: tastemaker-platform
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
